package kr.or.ddit.common;

public enum ServiceResult {
	OK, FAILED, EXIST, NOTEXIST, SAWFAILED, MEOFAILED, POFAILED, MTRFAILED, CLINICFAILED, MANYRESULTFAILED, MANYRECEIVEKEYFAILED, NOTUPDATE
}
